### ISSUE TITLE
WordLess Plugin

### ISSUE THREAD

**Issue by raffa96** [welaika/wordless#218] opened 2018-06-07 14:42 UTC
Hello everyone! As already reported to a member of Welaika, who then rightly asked me to report a problem on the problem found here on GitHub, I encountered the problem with an error after its first installation and then after creating a starter theme with the command I went to the folder of the theme and I gave the command wp server to start the local development server, I also tried with yarn (same thing) and also with the classic MAMP for MacOS but nothing ... So I was wondering if there someone would be able to deal with the problem and then help me solve it. Thanks in advance to everyone! (place the screenshots of the error below in the issue)

<img width="1101" alt="schermata 2018-06-07 alle 16 33 48" src="https://user-images.githubusercontent.com/21174464/41106716-e62652b8-6a70-11e8-9654-5cdb9c2f6043.png">
<img width="1440" alt="schermata 2018-06-07 alle 16 33 51" src="https://user-images.githubusercontent.com/21174464/41106717-e658b9b0-6a70-11e8-847d-a22629f96959.png">

**Comment by mukkoo** [comment] 2018-06-07 14:48
Hi @raffa96,
the error `Call to undefined function render_view()` seems related to non wordless plugin activation.
Can you verify if plugin is active?

**Comment by raffa96** [comment] 2018-06-07 16:18
Hi @mukkoo ,
yes the plugin is installed and correctly activated!
How now I show you below ...
<img width="1440" alt="schermata 2018-06-07 alle 18 15 26" src="https://user-images.githubusercontent.com/21174464/41112395-17a1159a-6a7f-11e8-838e-b52d7bffd656.png">

**Comment by pioneerskies** [comment] 2018-06-08 13:37
Hmmm... `wp theme create` is not creating the `tmp` dir inside the theme's directory.

You should solve with `mkdir /Applications/MAMP/htdocs/wordpress/wp-content/themes/winston/tmp`

I'll investigate about this behaviour

**Comment by pioneerskies** [comment] 2018-06-08 13:54
@raffa96 you should see also a warning like

```
PHP Warning:  Missing directories: theme is missing following directories: tmp. Fix theme or deactivate wordless plugin in /Users/fuzzy/dev/wpplain/wp-content/plugins/wordless/wordless/wordless.php on line 37
```

unless you have `WP_DEBUG` constant set to true. Aren't you?

**Comment by pioneerskies** [comment] 2018-06-08 14:51
Should be fixed in https://github.com/welaika/wordless/releases/tag/2.3.0.

Please retry the full process from the beginning - thus at least removing the created theme - and close this issue if the problem is solved.

Thanks for your contribution!

**Comment by raffa96** [comment] 2018-06-08 16:55
Hi @pioneerskies ,
I checked what was asked and before updating the plugin to the new version I manually created the tmp directory manually in the winston dir ... Immediately after I proceeded to update the plugin and everything worked properly.
Finally then I proceeded to carry out a further test creating a new project from scratch with the command theme create and the result of this is no longer the previous error but when I load the index page of the server I get the following message in the browser ...

**Comment by raffa96** [comment] 2018-06-09 08:46
Yes, you're absolutely right ... In fact yesterday I managed to start the server correctly and I have not had that initial problem ... But to compile the Sass file I have to give some particular command?

Anyway, thanks a lot for the efficient support!

**Comment by pioneerskies** [comment] 2018-06-10 16:29
> But to compile the Sass file I have to give some particular command?

Yes as I said:

> As far as I can understand now you should be ready to enter theme directory and launch yarn server (or at least invoking webpack once in order to test it with npx webpack).

`yarn server` is the standard approach to development: you have a server running, and webpack constantly watching and compiling you assets as per its configuration. Your code will be compiled and served every time you'll save a sass/coffee file and you browser automatically reloaded.
Pug templates are not compiled by webpack, but directly by a PHP library.

`npx webpack` will only ask webpack to compile assets and will exit; nothing more.

**Comment by raffa96** [comment] 2018-06-11 07:02
Perfect! Now no mistake or anything ... Thank you for the support! Good continuation and see you soon.

**Closed** 2018-06-11 07:03 UTC
